name             'chef-repo'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef-repo'
long_description 'Installs/Configures chef-repo'
version          '0.1.0'
