name             'cookbooks'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cookbooks'
long_description 'Installs/Configures cookbooks'
version          '0.1.0'
