Vagrant.configure("2") do |config|
  config.vm.box = "puphpet/ubuntu1404-x64"
  config.vm.network :forwarded_port, host: 5555, guest: 80
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.module_path = 'puppet/modules'
    puppet.manifest_file = 'init.pp'
  end
end

